// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoRequest struct {
	Name string `json:"name"`
}

type Result struct {
	Code string      `json:"code"`
	Data interface{} `json:"data"`
	Msg  string      `json:"msg"`
}
